### ISSUE TITLE
Error starting daemon

### ISSUE THREAD

**Issue by quartox** [jcrist/skein#7]
I am getting an error starting the daemon. The command line output is unhelpful `Error: Failed to start java process` but the log output appears potentially illuminating:

```
18/05/30 10:39:38 FATAL skein.Daemon: Error running Daemon
java.lang.IllegalArgumentException: ALPN is not configured properly. See https://github.com/grpc/grpc-java/blob/
master/SECURITY.md#troubleshooting for more information.
	at io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:166)
```

**Comment by jcrist** [comment]
Thanks for the issue report. I believe this to be a classpath conflict with the netty/grpc.netty libraries (as per https://github.com/grpc/grpc-java/blob/master/SECURITY.md#troubleshooting). If so, this should now be fixed on master (we now shade all relevant dependencies).

Are you able to try building the package locally? You need a maven install, and then `pip install -U https://github.com/jcrist/skein.git` should work. If you've already git cloned it, then the process is:

```
git pull origin master
python setup.py clean --all  # remove any prior build of the java source
pip install .
```

**Comment by quartox** [comment]
This is working to start the daemon, but the logs from the application master on the yarn cluster list the same error:

```
18/05/30 13:31:30 INFO skein.ApplicationMaster: Job successfully loaded:
18/05/30 13:31:30 INFO skein.ApplicationMaster: user: jlord:
18/05/30 13:31:31 INFO impl.NMClientAsyncImpl: Upper bound of the thread pool size is 500:
18/05/30 13:31:31 INFO internal.NativeLibraryLoader: /tmp/libcom_anaconda_skein_shaded_netty_tcnative_linux_x86_647406578869305479707.so exists but cannot be executed even when execute permissions set; check volume for "noexec" flag; use -Dio.netty.native.workdir=[path] to set native working directory separately.:
18/05/30 13:31:31 FATAL skein.ApplicationMaster: Error running ApplicationMaster:
java.lang.IllegalArgumentException: ALPN is not configured properly. See https://github.com/grpc/grpc-java/blob/master/SECURITY.md#troubleshooting for more information.
	at com.anaconda.skein.shaded.io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:166)
```

**Comment by jcrist** [comment]
Hmmm, [this issue](https://github.com/netty/netty/issues/6678) makes it appear to be due to noexec permissions set for `/tmp`. Working on a fix.

**Comment by jcrist** [comment]
Can you try #8?

**Comment by quartox** [comment]
I installed #8 but am still seeing the same issue.

`18/05/30 15:38:40 INFO internal.NativeLibraryLoader: /tmp/libcom_anaconda_skein_shaded_netty_tcnative_linux_x86_641197956660157000424.so exists but cannot be executed even when execute permissions set; check volume for "noexec" flag; use -Dio.netty.native.workdir=[path] to set native working directory separately.:
`

**Comment by jcrist** [comment]
Hmmmm, not sure then. I'll see if I can forbid execution of `/tmp` locally and try to reproduce.

**Comment by jcrist** [comment]
Ok, I was able to reproduce locally. For some reason the `-D` flag was being ignored. I couldn't determine why, so it's now specified programmatically which should be fine. Please try it again when you get a chance.

**Comment by quartox** [comment]
Works!

**Comment by jcrist** [comment]
Excellent. Let me know if you run into any other issues.
